import './Product.css';
const ProductDetails = [
    {
      id: 1,
      name: 'Zen Wall Home Lamps',
      price: '₹15,000.00',
      quantityAvailable: 10,
      imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/21-1-433x516.jpg',
    },
    {
      id: 2,
      name: 'Sculpted Pendant Lamps',
      price: '₹7,700.00',
      quantityAvailable: 15,
      imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/Pendantlight_mid_product-433x516.jpg',
    },
    {
        id: 3,
        name: 'Regal Candle Stand',
        price: '₹7,300.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/elephant_product1-433x516.jpg',
      },
      {
        id: 4,
        name: 'Nari Smoked Planter',
        price: '₹600.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/teapot_mid_product-433x516.jpg',
      },
      {
        id: 5,
        name: 'Painted Dinner Set',
        price: '₹4,900.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P8_2-433x516.jpg',
      },
      {
        id: 6,
        name: 'Hand-Carved mirror',
        price: '₹16,500.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/45-433x516.jpg',
      },
      {
        id: 7,
        name: 'Hand-Beaten Tea Set',
        price: '₹6,500.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/teapot_mid_product-433x516.jpg',
      },
      {
        id: 8,
        name: 'Eternal Tea light',
        price: '₹3,500.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/5-433x516.jpg',
      },
      {
        id: 9,
        name: 'Cinoni Clay Decanter',
        price: '₹2,300.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P2_2-433x516.jpg',
      },
      {
        id: 10,
        name: 'Brass embossed Planter',
        price: '₹5,500.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/lotus_vase_mid_product-433x516.jpg',
      },
      {
        id: 11,
        name: 'Bala Planter',
        price: '₹450.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/09/S1_3-433x516.jpg',
      },
      {
        id: 12,
        name: 'Badak Clay Decanter',
        price: '₹2,000.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/Painted-Waterbottle-433x516.jpg',
      },
      {
        id: 13,
        name: 'Hand Decorated Glass',
        price: '₹350.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2020/08/P4_3-433x516.jpg',
      },
      {
        id: 14,
        name: 'Painted Dinner Set',
        price: '₹4,900.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P8_2-433x516.jpg',
      },
      {
        id: 15,
        name: 'Painted Serving Bowl',
        price: '₹1,800.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P7_6-433x516.jpg',
      },
      {
        id: 16,
        name: 'Jewellery Keeper',
        price: '₹1,300.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P7_6-433x516.jpg',
      },
      {
        id: 17,
        name: 'Khavda Tea Set',
        price: '₹2,500.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P3_2-433x516.jpg',
      },
      {
        id: 18,
        name: 'Khavda Water Bottle',
        price: '₹1,200.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P6_1-433x516.jpg',
      },
      {
        id: 19,
        name: 'Martaban Dispenser',
        price: '₹2,100.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/11/P4_2-433x516.jpg',
      },
      {
        id: 20,
        name: 'Beetle Leaf Plate Set',
        price: '₹5,300.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/leaf_bowl_mid_product-433x516.jpg',
      },
      {
        id: 21,
        name: 'Brass Wind Chime',
        price: '₹2,900.00',
        quantityAvailable: 15,
        imageUrl: 'https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img,w_433,h_516/https://akkaara.co.in/wp-content/uploads/2019/01/wind_chime_mid_product-433x516.jpg',
      },

  ];
  
  export default ProductDetails;
  